### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by dima12qw** [promptworks/tenantex#14]
Hey,could you help me with the authentication? I have no ideea how can I do that in multi tenant application.

**Comment by dima12qw** [comment]
And how can I set up the endpoints for an user?

**Comment by jeffdeville** [comment]
That's a pretty broad question. Conceptually, I think your steps here are going to be:

1. Choose an authentication library.  (Guardian or coherence)
2. You'll want to follow whatever their guidelines are, but move the migrations they generate into your multi-tenant migrations folder instead.
3. Create your tenants however you wish.  Not sure how to advise you here, since I'm not sure what you're building, but a seeds.exs file would make sense to at least create an admin tenant with an admin user
4. If you're doing a web app, the usual pattern is to choose the tenant by subdomain.  You can create a plug that will drop that into your 'conn'.  (Example of this plug below)
5. You'll then grab that value in your controller actions (`def show(%{assigns: %{tenant: tenant}} = conn, params) do` for example.  Now you'll have your tenant, which if you're using Ecto 2.1+ (I think that's the version) should be easy to use by passing it in as a prefix. 

```elixir
defmodule Api.Web.Plug.Subdomain do
  import Plug.Conn

  @doc false
  def init(default), do: default

  @doc false
  def call(conn, router) do
    case get_subdomain(conn.host) do
      subdomain when byte_size(subdomain) > 0 ->
        conn
        |> assign(:tenant, subdomain)
        |> router.call(router.init({}))
        |> halt
      _ -> conn
    end
  end

  defp get_subdomain(host) do
    host |> String.split(".") |> List.first
  end
end
```

Hope that helps.
